### ISSUE TITLE
Database Result Errors - 3 endpoints /dailyPrice, /cmcTotalDailyVolume, /trade/{market_pair}

### ISSUE THREAD

**Issue by hungng157** [Sifchain/sif-apis#13]
It seems like the results from responses of those 3 endpoints are incorrect although the server responded with status 200.

<img width="1412" alt="Screen Shot 2022-06-29 at 4 51 45 PM" src="https://user-images.githubusercontent.com/107917651/176408115-932d092b-270e-4f09-a91b-207df63c29c0.png">
<img width="1391" alt="Screen Shot 2022-06-29 at 4 52 05 PM" src="https://user-images.githubusercontent.com/107917651/176408146-97584494-ed25-43fd-8694-dd5792817d3a.png">
<img width="1396" alt="Screen Shot 2022-06-29 at 4 52 41 PM" src="https://user-images.githubusercontent.com/107917651/176408156-cd8f1055-1e3d-45e3-9fe4-cf8e8585074f.png">
<img width="997" alt="Screen Shot 2022-06-29 at 4 53 12 PM" src="https://user-images.githubusercontent.com/107917651/176408160-41327f4a-f1a7-48ea-a56b-2051e2b6b97c.png">

**Comment by sx0785** [comment]
@lufa23 @hungng157 got data in db now for `select trading_pairs, highest_price_24h,lowest_price_24h, last_price, opening, price_change_percent_24h,base_currency, target_currency, base_volume, target_volume, bid, ask, liquidity_in_usd from trade_daily_temp`
![image](https://user-images.githubusercontent.com/36971061/176776547-84419c72-84ec-4912-bdbb-7e63a0fcc0a3.png)

can you please try the `/dailyPrice` again?

**Comment by sx0785** [comment]
![image](https://user-images.githubusercontent.com/36971061/176777884-1cc46ca8-62ff-47c1-8655-f614b5e776ac.png)
`select
hash,
swap_begin_token,
swap_final_token,
swap_begin_amount as base_volume,
swap_final_amount as target_volume,
time as timestamp
from events_audit
where time >= NOW() - INTERVAL '24 HOURS'
and type='swap_successful';`

also has data now. **still syncing data from prod to opensource db and will let you know once done**

**Comment by sx0785** [comment]
![image](https://user-images.githubusercontent.com/36971061/176778672-bcbb59c6-30c2-4d76-be56-212a6e48eab2.png)

> select p.asset as tickerID, 
          left(p.asset, length(p.asset)-6) as base_currency,
          'rowan' as target_currency,
          p.last as last_price,
          b.volume as base_volume,
          t.rowan_vol as target_volume,
          p.last - p.last * 0.002 as bid,
          p.last as ask,
          p.high,
          p.low
          from (select time_bucket('1 Day', time) as daily,
            asset,
              first(asset_price, time) as opening,
              max(asset_price) as high,
              min(asset_price) as low,
              last(asset_price, time) as last
          from TokenPrices
          where 
          time > now() - interval '1 Day'
          and asset like '%_rowan'
          group by daily, asset
          ) p inner join 
          (	select time_bucket('1 Day', time) as daily, 
            last(asset_volume_daily, time) as rowan_vol from tokenvolumes where asset = 'rowan'
            group by daily
            ) t
            on p.daily = t.daily
          left join 
          ( select time_bucket('1 Day', time) as daily,
              asset,
              last(asset_volume_daily, time) as volume
            from TokenVolumes 
            where time > now() - interval '1 Day'
            and asset <> 'rowan'
            group by daily, asset
          ) b on p.daily = b.daily
          and p.asset = b.asset || '_rowan'
          order by p.daily desc

**Comment by hungng157** [comment]
All the endpoints worked now.
